### ISSUE TITLE
Almost everything is seen as OK with default settings

### ISSUE THREAD

**Issue by JulienMaille** [seanXYZ/SegDecNet#3]
I trained segmentation and then decision with your default settings and the network barely detect anything. I get 99% of "OK" on the test dataset.
Did I missed something?

**Comment by eric-tc** [comment]
Hi,
i have the same behaviour. Did you find an answer?

**Comment by JulienMaille** [comment]
Not really, I tried to setup a Google Colab notebook.
https://colab.research.google.com/drive/101HUaOo3PskWp7h6DucR50pIGxO_SX2m
The loss during training doesn't look good to me

**Comment by eric-tc** [comment]
Hi,

i got it working. When you train the segmentation network please use only the defect inside Train_NG with lr 0.001. Train it for 100 epochs as default. When you train the decision network change the lr=0.1 with Adam or add some lr_scheduler like cycle learning. With these parameters i got both defect and good classification. Let me know if it is working also for you. Thanks

**Comment by JulienMaille** [comment]
Ok I will try that. Have you tried training it on your own dataset?

**Comment by eric-tc** [comment]
Yes i have tried but with no good results

**Comment by SampleW** [comment]
when i using defualt settings in training, the output mask in "testResultSeg" is completely black, no defect was detected,same In all pictures of all epoch (100 epoch ). 
How can i fix it. 
thanks.

**Comment by ShaneYS** [comment]
> 
> 
> when i using defualt settings in training, the output mask in "testResultSeg" is completely black, no defect was detected,same In all pictures of all epoch (100 epoch ).
> How can i fix it.
> thanks.

hi, I have the same problem(the output mask in "testResultDec" is completely black), have you sovled it?

**Comment by eric-tc** [comment]
Hi @SampleW ,

have you tried with the images provided or with your own dataset?

**Comment by LoveIsAGame** [comment]
ValueError: num_samples should be a positive integer value, but got num_samples=0
how can i fix it?

**Comment by LoveIsAGame** [comment]
@eric-tc 
@neFAST

**Comment by molyswu** [comment]
@LoveIsAGame     
 The same problem, how do you solve it？

**Comment by molyswu** [comment]
Tried  to  python train_segment.py
ValueError: num_samples should be a positive integer value, but got num_samples=0
  
THANKS

**Comment by molyswu** [comment]
Changed  ".jpg"  to ".bmp"      at dataset.py .

ok

**Comment by elepp** [comment]
try to use sigmoid but not rule in the last which is named layer 5

**Comment by 1ylwang** [comment]
oh,Tried to python train_segment.py is ok, but tried to python train_decision.py  is ValueError: num_samples should be a positive integer value, but got num_samples=0, why? how do you solve it?
thanks.

**Comment by Manoj-Paladugu** [comment]
> Hi @SampleW ,
> 
> have you tried with the images provided or with your own dataset?

Hi @eric-tc ,
I have trained with the included dataset but I can't seem to detect anything either (it's always black). As you suggested I have also ensured to train seg network with lr 0.001. I feel pretty lost :/  Do you by any chance have a forked repo with the working parameters that you can share?

**Comment by ghost** [comment]
> 
> 
> try to use sigmoid but not rule in the last which is named layer 5

Still not working. I doubt the implementation can work tbh

**Comment by DCC-lzhy** [comment]
> > try to use sigmoid but not rule in the last which is named layer 5
> 
> Still not working. I doubt the implementation can work tbh
just no act function，because loss function has the act.
